
    # Necesito chequear que la m치quina sea UBUNTU... ya que si no es CIERRO EL GRIFO !
-   name:       Asegurarme que estoy en una m치quina UBUNTU
    # ACABAR EL PLAY.
    meta: end_host
    when: # Si no estoy en una m치quina UBUNTU
          # Y de donde lo saco? ansible_facts... los tengo? NO
        # Pues habr침a que conseguirlos: Opciones:
        # 1: gather_facts -> true       Esto es pa' los novatos de ansible.
                                        # Nosotros somo pro !
        # 2: pedir los datos que necesito
        - ansible_facts.distribution != "Ubuntu"
    tags: 
        - obligatorio