# Quiero instalar el servidor web nginx y lo quiero montar en máquinas UBUNTU
# Lo único que quiero dejar el nginx funcionando en un puerto de mi interés
# Quiero poder trabajar con mi propio document root
# Que se rellene con los ficheros que tengamos en un repo de git
# https://github.com/IvanciniGT/webEjemploAnsible
# RESPETANDO EL PRINCIPIO DE IDEMPOTENCIA !

-   hosts:              localhost
    gather_facts:       false
    vars:
        nginx:
            version: 
        app:
            repo:
            document_root:
            puerto:
            test:
                -   url:
                    response:
                -   url:
                    response:
      
    pre_tasks:
        -   name:       Asegurarme que estoy en una máquina UBUNTU

        -   name:       Asegurarme que los repos de ubuntu de apt están actualizados

        -   name:       Asegurarme que tengo instalado git

        -   name:       Asegurarme que tengo instalado curl

    tasks:
        -   name:       Asegurarme que el servicio de nginx está detenido si debe estarlo
            block:
                -   name:   ???

        -   name:       Asegurarme que tal versión de nginx está instalada

        -   name:       Asegurarme que el nginx tiene la configuración que quiero

        -   name:       Asegurarme que tengo un servicio de nginx

        -   name:       "Guardar en algún sitio la versión que ahora mismo estaba en funcionamiento : TAG de GIT"

        -   name:       Asegurarme que tengo en la carpeta de marras descargada la ultima version del repo de git de turno
            notify:     CONTENIDO_APP_CAMBIADO

        -   name:       Asegurarme que el servicio de nginx está levantado

    post_tasks:
        -   name:       Pruebas de humo
            block: 
                -   name:   Asegurarme que la máquina tiene conectividad
        
                -   name:   Asegurarme que nginx está arriba
        
                -   name:   Asegurarme que nginx esta sirviendo la app

                -   name:   Notificacion ok
            rescue:
                -   name:   Notificacion error
            
    handlers:
        name:           Reinicio del servicio de nginx
        listen:
                      - CONTENIDO_APP_CAMBIADO

# Qué nombre damos a las tareas en ansible, VERBOS en imperativo? o en infinitivo. NO
## SIEMPRE RESPETANDO EL CONCEPTO DE IDEMPOTENCIA !
# De paso... teniendo en cuenta que NO LA LIO EN PRODUCCION !

# Quien podría llamar al script? 
#   Automáticamente por patrte de un servidor de automatición: JENKINS
# Ante qué eventos? 
    # Actualización del repo
    # Cambio en la confg de nginx
    # Quiera subir a una version de nginx
    # sistema de monitorización: Maquina KO -> 
    # Añadir máquinas ESCALAR

# Firewall



---
#Tareas pendientes
REQUISITO:
    - Saber lo que estoy automatizando y cómo es ese proceso... Mas me vale haberlo hecho alguna que otra vez
    - Si no voy más perdido que una rosquilla en el desierto !

TODO:
    - Reestructurar mejor las variables     > Cuando sepa qué variables (REFACTORIZACION))
    - Investigar los módulos... cuando vaya a escribir los módulos !
        - Ponerme como loco a escribir modulos  > Si... pero quizás no aún
    - Dar valores INICIALES a las variables > Cuando pruebe

Podríamos crear un play DUMMY, con la estructura pero haga na' > NO ESTA MAL...


DONE:
    - Estructura de tareas (play)
    - Variables previas que se me han ocurrido y su estructura
    - Lógica del play ? 
        when
        loop
        tag